"""
train.py

Fine-tunes Stable Video Diffusion (SVD) with LoRA adapters on the
pixel landslide training dataset generated by create_landslide_traindata.py.

Uses HuggingFace Diffusers + PEFT for efficient LoRA fine-tuning with
Accelerate for distributed training support.

Can operate in two modes:
  1. Standard (--batch-mode off): Train on pre-generated data
     accelerate launch train.py --data-dir data/training --num-epochs 50

  2. Batch (--batch-mode on): Generate 5 images -> train -> repeat
     accelerate launch train.py --batch-mode --images-dir data/raw-images \\
         --data-dir data/training --batch-size 5 --num-epochs 10
"""

import os
import json
import argparse
import logging
from pathlib import Path
from typing import Optional, Tuple

from torch.optim.lr_scheduler import CosineAnnealingLR

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import numpy as np
from PIL import Image
from tqdm import tqdm

from accelerate import Accelerator
from accelerate.logging import get_logger
from accelerate.utils import set_seed

from diffusers import StableVideoDiffusionPipeline
from diffusers.models import UNetSpatioTemporalConditionModel
from diffusers.training_utils import EMAModel

from peft import LoraConfig, get_peft_model
from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection

# Import batch processing functions
from create_landslide_traindata import process_image_batch
from download_images import get_image_batch

logger = get_logger(__name__, log_level="INFO")


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class LandslideDataset(Dataset):
    """
    PyTorch Dataset that loads (source_image, video_frames) pairs.

    Expects training data in the format produced by create_landslide_traindata.py:
        data_dir/
            source_{name}.png
            frames_{name}/
                frame_00000.png
                frame_00001.png
                ...
    """

    def __init__(
        self,
        data_dir: str,
        num_frames: int = 14,
        image_size: Tuple[int, int] = (512, 512),
    ) -> None:
        """
        Initialize the dataset.

        Args:
            data_dir: Root directory containing training data
            num_frames: Number of video frames to use per sample
            image_size: (height, width) for resizing images
        """
        self.data_dir = Path(data_dir)
        self.num_frames = num_frames
        self.image_size = image_size

        # Find all source images and pair them with frame directories
        self.samples = []
        for source_path in sorted(self.data_dir.glob("source_*.png")):
            name = source_path.stem.replace("source_", "", 1)
            frames_dir = self.data_dir / f"frames_{name}"
            if frames_dir.exists():
                frame_files = sorted(frames_dir.glob("frame_*.png"))
                if len(frame_files) >= num_frames:
                    self.samples.append((source_path, frame_files))

        logger.info(f"Found {len(self.samples)} training samples in '{data_dir}'")

        self.image_transform = transforms.Compose([
            transforms.Resize(image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
        ])

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict:
        """
        Load a single training sample.

        Returns:
            Dict with:
                - 'source_image': Tensor [3, H, W] (normalized)
                - 'frames': Tensor [T, 3, H, W] (normalized video frames)
        """
        source_path, frame_files = self.samples[idx]

        # Load source image
        source_img = Image.open(source_path).convert("RGB")
        source_tensor = self.image_transform(source_img)

        # Load evenly spaced frames from the sequence
        frame_indices = torch.linspace(0, len(frame_files) - 1, self.num_frames).long()
        frames = []
        for i in frame_indices:
            frame = Image.open(frame_files[i]).convert("RGB")
            frames.append(self.image_transform(frame))

        frames_tensor = torch.stack(frames)  # [T, 3, H, W]

        return {
            "source_image": source_tensor,
            "frames": frames_tensor,
        }


# ---------------------------------------------------------------------------
# LoRA Setup
# ---------------------------------------------------------------------------

def setup_lora(unet: UNetSpatioTemporalConditionModel, lora_rank: int = 32) -> UNetSpatioTemporalConditionModel:
    """
    Apply LoRA adapters to the UNet.

    Args:
        unet: The SVD UNet model
        lora_rank: LoRA rank (higher = more parameters, better quality)

    Returns:
        UNet with LoRA adapters attached
    """
    lora_config = LoraConfig(
        r=lora_rank,
        lora_alpha=lora_rank,
        target_modules=["to_k", "to_q", "to_v", "to_out.0"],
        lora_dropout=0.0,
        bias="none",
    )
    unet = get_peft_model(unet, lora_config)
    unet.print_trainable_parameters()
    return unet


# ---------------------------------------------------------------------------
# Training Loop
# ---------------------------------------------------------------------------

def train(args: argparse.Namespace) -> None:
    """
    Main training function (standard mode: train on pre-generated data).

    Args:
        args: Parsed command line arguments
    """
    # Initialize Accelerator for distributed training and mixed precision
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with="tensorboard" if args.report_to == "tensorboard" else None,
        project_dir=args.output_dir,
    )

    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )
    logger.info(accelerator.state, main_process_only=False)

    if args.seed is not None:
        set_seed(args.seed)

    # Create output directory
    output_dir = Path(args.output_dir)
    if accelerator.is_main_process:
        output_dir.mkdir(parents=True, exist_ok=True)

    # ---------------------------------------------------------------------------
    # Load base SVD model components
    # ---------------------------------------------------------------------------
    logger.info(f"Loading base model: {args.base_model}")

    pipeline = StableVideoDiffusionPipeline.from_pretrained(
        args.base_model,
        torch_dtype=torch.float16 if args.mixed_precision == "fp16" else torch.float32,
    )

    # We only train the UNet; freeze VAE and image encoder
    vae = pipeline.vae
    image_encoder = pipeline.image_encoder
    unet = pipeline.unet
    scheduler = pipeline.scheduler
    feature_extractor = pipeline.feature_extractor

    vae.requires_grad_(False)
    image_encoder.requires_grad_(False)

    # Apply LoRA to UNet
    logger.info(f"Applying LoRA (rank={args.lora_rank}) to UNet...")
    unet = setup_lora(unet, lora_rank=args.lora_rank)

    # Enable gradient checkpointing to save memory
    if args.gradient_checkpointing:
        unet.enable_gradient_checkpointing()

    # ---------------------------------------------------------------------------
    # Dataset and DataLoader
    # ---------------------------------------------------------------------------
    dataset = LandslideDataset(
        data_dir=args.data_dir,
        num_frames=args.num_frames,
        image_size=(args.image_size, args.image_size),
    )

    if len(dataset) == 0:
        raise ValueError(f"No training samples found in '{args.data_dir}'. "
                         "Run create_landslide_traindata.py first.")

    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.dataloader_num_workers,
        pin_memory=True,
    )

    # ---------------------------------------------------------------------------
    # Optimizer
    # ---------------------------------------------------------------------------
    optimizer = torch.optim.AdamW(
        unet.parameters(),
        lr=args.learning_rate,
        betas=(0.9, 0.999),
        weight_decay=1e-2,
        eps=1e-8,
    )

    # LR scheduler: cosine decay with warmup
    lr_scheduler = CosineAnnealingLR(optimizer, T_max=args.num_epochs * len(dataloader))

    # ---------------------------------------------------------------------------
    # Prepare with Accelerator
    # ---------------------------------------------------------------------------
    unet, optimizer, dataloader, lr_scheduler = accelerator.prepare(
        unet, optimizer, dataloader, lr_scheduler
    )

    vae = vae.to(accelerator.device)
    image_encoder = image_encoder.to(accelerator.device)

    # ---------------------------------------------------------------------------
    # Resume from checkpoint
    # ---------------------------------------------------------------------------
    first_epoch = 0
    global_step = 0

    if args.resume_from is not None:
        resume_path = Path(args.resume_from)
        if resume_path.exists():
            logger.info(f"Resuming from checkpoint: {args.resume_from}")
            accelerator.load_state(args.resume_from)
            # Parse epoch from checkpoint name if possible
            try:
                first_epoch = int(resume_path.name.split("_epoch_")[-1]) + 1
            except (ValueError, IndexError):
                pass
        else:
            logger.warning(f"Checkpoint not found: {args.resume_from}, starting fresh")

    # ---------------------------------------------------------------------------
    # Training Loop
    # ---------------------------------------------------------------------------
    logger.info(f"Starting training: {args.num_epochs} epochs, {len(dataset)} samples")

    for epoch in range(first_epoch, args.num_epochs):
        unet.train()
        epoch_loss = 0.0

        progress_bar = tqdm(
            dataloader,
            desc=f"Epoch {epoch + 1}/{args.num_epochs}",
            disable=not accelerator.is_local_main_process,
        )

        for step, batch in enumerate(progress_bar):
            with accelerator.accumulate(unet):
                source_images = batch["source_image"]  # [B, 3, H, W]
                video_frames = batch["frames"]          # [B, T, 3, H, W]

                B, T, C, H, W = video_frames.shape

                # Encode source images with CLIP image encoder
                with torch.no_grad():
                    # Normalize to [0, 1] for CLIP feature extractor
                    source_pil = (source_images * 0.5 + 0.5).clamp(0, 1)
                    source_pil = (source_pil * 255).byte()

                    # Process each image in the batch
                    clip_inputs = []
                    for i in range(B):
                        pil_img = Image.fromarray(
                            source_pil[i].permute(1, 2, 0).cpu().numpy()
                        )
                        processed = feature_extractor(pil_img, return_tensors="pt")
                        clip_inputs.append(processed.pixel_values)

                    clip_pixel_values = torch.cat(clip_inputs, dim=0).to(accelerator.device)
                    image_embeddings = image_encoder(clip_pixel_values).image_embeds
                    # Add sequence dimension: [B, 1, D]
                    image_embeddings = image_embeddings.unsqueeze(1)

                # Encode video frames to latents using VAE
                with torch.no_grad():
                    # Flatten batch and time dims for VAE encoding
                    frames_flat = video_frames.view(B * T, C, H, W)
                    latents = vae.encode(frames_flat).latent_dist.sample()
                    latents = latents * vae.config.scaling_factor
                    # Reshape back: [B, T, latent_C, latent_H, latent_W]
                    _, lC, lH, lW = latents.shape
                    latents = latents.view(B, T, lC, lH, lW)

                # Rearrange for UNet: [B, lC, T, lH, lW]
                latents = latents.permute(0, 2, 1, 3, 4)

                # Sample noise and timesteps
                noise = torch.randn_like(latents)
                timesteps = torch.randint(
                    0, scheduler.config.num_train_timesteps,
                    (B,), device=accelerator.device
                ).long()

                # Add noise to latents
                noisy_latents = scheduler.add_noise(latents, noise, timesteps)

                # Prepare added time embedding (motion bucket id + fps)
                added_time_ids = _get_add_time_ids(
                    fps=args.fps,
                    motion_bucket_id=127,
                    noise_aug_strength=0.02,
                    batch_size=B,
                    device=accelerator.device,
                    dtype=latents.dtype,
                )

                # Encode conditioning frames (source image as video conditioning)
                with torch.no_grad():
                    source_latents = vae.encode(source_images).latent_dist.sample()
                    source_latents = source_latents * vae.config.scaling_factor
                    # Repeat for each timestep: [B, lC, 1, lH, lW] -> [B, lC, T, lH, lW]
                    _, slC, slH, slW = source_latents.shape
                    source_latents = source_latents.unsqueeze(2).expand(-1, -1, T, -1, -1)

                # Concatenate conditioning with noisy latents on channel dim
                latent_model_input = torch.cat([noisy_latents, source_latents], dim=1)

                # UNet forward pass
                noise_pred = unet(
                    latent_model_input,
                    timesteps,
                    encoder_hidden_states=image_embeddings,
                    added_time_ids=added_time_ids,
                    return_dict=False,
                )[0]

                # Compute loss (MSE between predicted and actual noise)
                loss = F.mse_loss(noise_pred, noise, reduction="mean")

                accelerator.backward(loss)

                if accelerator.sync_gradients:
                    accelerator.clip_grad_norm_(unet.parameters(), 1.0)

                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()

            if accelerator.sync_gradients:
                global_step += 1

            epoch_loss += loss.detach().item()
            progress_bar.set_postfix({"loss": f"{loss.detach().item():.4f}"})

        avg_loss = epoch_loss / len(dataloader)
        logger.info(f"Epoch {epoch + 1}/{args.num_epochs} | Loss: {avg_loss:.4f}")

        # Save checkpoint periodically
        if accelerator.is_main_process and (epoch + 1) % args.save_every == 0:
            ckpt_dir = output_dir / f"lora_epoch_{epoch + 1}"
            _save_lora_weights(accelerator.unwrap_model(unet), str(ckpt_dir))
            logger.info(f"Checkpoint saved: {ckpt_dir}")

    # Save final LoRA weights
    if accelerator.is_main_process:
        final_dir = output_dir / "lora_final"
        _save_lora_weights(accelerator.unwrap_model(unet), str(final_dir))
        logger.info(f"Final LoRA weights saved to: {final_dir}")

    accelerator.end_training()


def batch_training_pipeline(args: argparse.Namespace) -> None:
    """
    Batch-based training: generate images in batches, train on each batch sequentially.

    Workflow:
      1. Load raw images from images_dir
      2. Get next unprocessed batch (batch_size images)
      3. Generate training data via process_image_batch()
      4. Train for num_epochs on that batch
      5. Save checkpoint
      6. Track progress in JSON
      7. Repeat until all images processed or batches limit reached

    Args:
        args: Parsed command line arguments
    """
    logger.info("=== BATCH TRAINING PIPELINE ===")
    logger.info(f"Mode: Batch training")
    logger.info(f"Batch size: {args.batch_size}")
    logger.info(f"Epochs per batch: {args.num_epochs}")
    logger.info(f"Images dir: {args.images_dir}")
    logger.info(f"Data dir: {args.data_dir}")
    logger.info(f"Batch progress file: {args.batch_progress_file}")

    # Load progress
    progress = _load_batch_progress(args.batch_progress_file)
    last_batch_idx = progress.get("last_batch_idx", -1)
    images_processed = progress.get("images_processed", 0)
    checkpoints = progress.get("checkpoints_saved", [])

    # Count total images
    from pathlib import Path
    image_dir = Path(args.images_dir)
    patterns = ["*.jpg", "*.jpeg", "*.JPG", "*.JPEG", "*.png", "*.PNG", "*.HEIC", "*.heic"]
    all_images = []
    for pattern in patterns:
        all_images.extend(sorted(image_dir.glob(pattern)))
    all_images = sorted(set(all_images))
    total_images = len(all_images)

    logger.info(f"Total images available: {total_images}")

    batch_idx = 0
    current_image_idx = 0

    # Process batches
    while current_image_idx < total_images:
        if args.batches_to_process is not None and batch_idx >= args.batches_to_process:
            logger.info(f"Reached batch limit ({args.batches_to_process}), stopping.")
            break

        logger.info(f"\n{'='*60}")
        logger.info(f"BATCH {batch_idx + 1}")
        logger.info(f"{'='*60}")

        # Get batch of images
        batch_image_paths = get_image_batch(args.images_dir, args.batch_size, current_image_idx)
        
        if not batch_image_paths:
            logger.info("No more images to process.")
            break

        logger.info(f"Processing {len(batch_image_paths)} images in this batch...")

        # Generate training data for this batch
        process_image_batch(
            batch_image_paths,
            args.data_dir,
            duration=args.duration,
            fps=args.fps,
            target_width=args.target_width,
            target_height=args.target_height,
        )

        # Train on this batch
        logger.info(f"Training for {args.num_epochs} epochs on this batch...")
        train(args)

        # Save progress
        current_image_idx += len(batch_image_paths)
        batch_idx += 1
        images_processed = current_image_idx
        checkpoint_name = f"lora_batch_{batch_idx}"
        checkpoints.append(checkpoint_name)

        progress = {
            "last_batch_idx": batch_idx - 1,
            "images_processed": images_processed,
            "total_images": total_images,
            "checkpoints_saved": checkpoints,
        }
        _save_batch_progress(progress, args.batch_progress_file)

        logger.info(f"Batch {batch_idx} complete. Progress: {images_processed}/{total_images} images")

    logger.info(f"\n{'='*60}")
    logger.info("BATCH PIPELINE COMPLETE")
    logger.info(f"Total images processed: {images_processed}/{total_images}")
    logger.info(f"Checkpoints saved: {len(checkpoints)}")
    logger.info(f"{'='*60}")


def _load_batch_progress(progress_file: str) -> dict:
    """Load batch progress from JSON file, or return empty dict."""
    try:
        with open(progress_file, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}


def _save_batch_progress(progress: dict, progress_file: str) -> None:
    """Save batch progress to JSON file."""
    Path(progress_file).parent.mkdir(parents=True, exist_ok=True)
    with open(progress_file, "w") as f:
        json.dump(progress, f, indent=2)


def _get_add_time_ids(
    fps: int,
    motion_bucket_id: int,
    noise_aug_strength: float,
    batch_size: int,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    """
    Build the added time embedding tensor for SVD conditioning.

    Args:
        fps: Frames per second
        motion_bucket_id: Motion bucket ID for conditioning
        noise_aug_strength: Augmentation noise strength
        batch_size: Batch size
        device: Target device
        dtype: Target dtype

    Returns:
        Tensor of shape [B, 3]
    """
    add_time_ids = [fps - 1, motion_bucket_id, noise_aug_strength]
    add_time_ids = torch.tensor([add_time_ids], dtype=dtype, device=device)
    add_time_ids = add_time_ids.repeat(batch_size, 1)
    return add_time_ids


def _save_lora_weights(unet: UNetSpatioTemporalConditionModel, save_dir: str) -> None:
    """
    Save LoRA weights to disk.

    Args:
        unet: The UNet model (with LoRA adapters)
        save_dir: Directory to save weights
    """
    Path(save_dir).mkdir(parents=True, exist_ok=True)
    unet.save_pretrained(save_dir)


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Fine-tune Stable Video Diffusion with LoRA on landslide training data"
    )

    # Data arguments
    parser.add_argument("--data-dir", type=str, required=True,
                        help="Directory with training data from create_landslide_traindata.py")
    parser.add_argument("--output-dir", type=str, default="checkpoints",
                        help="Directory for saving checkpoints (default: checkpoints)")
    parser.add_argument("--base-model", type=str,
                        default="stabilityai/stable-video-diffusion-img2vid",
                        help="HuggingFace model ID for the base SVD model")
    parser.add_argument("--resume-from", type=str, default=None,
                        help="Path to a checkpoint to resume training from")

    # Training hyperparameters
    parser.add_argument("--num-epochs", type=int, default=50,
                        help="Number of training epochs (default: 50)")
    parser.add_argument("--learning-rate", type=float, default=1e-4,
                        help="Learning rate (default: 1e-4)")
    parser.add_argument("--batch-size", type=int, default=1,
                        help="Per-device batch size (default: 1)")
    parser.add_argument("--gradient-accumulation-steps", type=int, default=4,
                        help="Gradient accumulation steps (default: 4)")
    parser.add_argument("--mixed-precision", type=str, default="fp16",
                        choices=["no", "fp16", "bf16"],
                        help="Mixed precision training (default: fp16)")
    parser.add_argument("--gradient-checkpointing", action="store_true",
                        help="Enable gradient checkpointing to save memory")
    parser.add_argument("--dataloader-num-workers", type=int, default=4,
                        help="Number of DataLoader workers (default: 4)")

    # LoRA arguments
    parser.add_argument("--lora-rank", type=int, default=32,
                        help="LoRA rank (default: 32)")

    # Video arguments
    parser.add_argument("--num-frames", type=int, default=14,
                        help="Number of video frames per sample (default: 14)")
    parser.add_argument("--image-size", type=int, default=512,
                        help="Image size in pixels (default: 512)")
    parser.add_argument("--fps", type=int, default=14,
                        help="Frames per second for conditioning (default: 14)")

    # Logging and checkpointing
    parser.add_argument("--save-every", type=int, default=5,
                        help="Save checkpoint every N epochs (default: 5)")
    parser.add_argument("--report-to", type=str, default="tensorboard",
                        choices=["tensorboard", "none"],
                        help="Where to log training metrics (default: tensorboard)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for reproducibility (default: 42)")

    # Batch training arguments
    parser.add_argument("--batch-mode", action="store_true",
                        help="Enable batch-based training pipeline (generate -> train -> repeat)")
    parser.add_argument("--images-dir", type=str, default=None,
                        help="Directory with raw source images (required for batch-mode)")
    parser.add_argument("--batch-progress-file", type=str, default="batch_progress.json",
                        help="Path to JSON file tracking batch progress (default: batch_progress.json)")
    parser.add_argument("--batches-to-process", type=int, default=None,
                        help="Limit number of batches to process (default: None = all)")
    
    # Data generation arguments (for batch mode)
    parser.add_argument("--duration", type=int, default=4,
                        help="Video duration in seconds for generated data (default: 4)")
    parser.add_argument("--target-width", type=int, default=512,
                        help="Target image width in pixels for generated data (default: 512)")
    parser.add_argument("--target-height", type=int, default=512,
                        help="Target image height in pixels for generated data (default: 512)")

    args = parser.parse_args()

    # Route to appropriate training mode
    if args.batch_mode:
        if args.images_dir is None:
            raise ValueError("--images-dir is required when using --batch-mode")
        batch_training_pipeline(args)
    else:
        train(args)


if __name__ == "__main__":
    main()