"""
train.py

Fine-tunes Stable Video Diffusion (SVD) with LoRA adapters on the
pixel landslide training dataset generated by create_landslide_traindata.py.

Batch training workflow:
  1. Download 5 new images from Wikimedia Commons
  2. Generate training data (frames + videos)
  3. If first run: Create model from scratch
     Else: Load existing checkpoint and update with new data
  4. Train for 1 epoch on the new batch
  5. Clear training data directory
  6. Repeat until total_epochs == total_images_processed

Usage:
    accelerate launch train.py \\
        --data-dir data/training \\
        --images-dir data/raw-images \\
        --output-dir checkpoints \\
        --num-epochs 300 \\
        --batch-size 5
"""

import os
import json
import argparse
import logging
import shutil
from pathlib import Path
from typing import Optional, Tuple

from torch.optim.lr_scheduler import CosineAnnealingLR

import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import numpy as np
from PIL import Image
from tqdm import tqdm

from accelerate import Accelerator, PartialState
from accelerate.logging import get_logger
from accelerate.utils import set_seed

from diffusers import StableVideoDiffusionPipeline
from diffusers.models import UNetSpatioTemporalConditionModel
from diffusers.training_utils import EMAModel

from peft import LoraConfig, get_peft_model
from transformers import CLIPImageProcessor, CLIPVisionModelWithProjection

# Import batch processing functions
from create_landslide_traindata import process_image_batch
from download_images import search_wikimedia_images, extract_image_info, download_image, load_attributions, save_attributions

# Initialize logger with PartialState to avoid early initialization issues
_ = PartialState()
logger = get_logger(__name__, log_level="INFO")


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class LandslideDataset(Dataset):
    """
    PyTorch Dataset that loads (source_image, video_frames) pairs.

    Expects training data in the format produced by create_landslide_traindata.py:
        data_dir/
            source_{name}.png
            frames_{name}/
                frame_00000.png
                frame_00001.png
                ...
    """

    def __init__(
        self,
        data_dir: str,
        num_frames: int = 14,
        image_size: Tuple[int, int] = (512, 512),
    ) -> None:
        """
        Initialize the dataset.

        Args:
            data_dir: Root directory containing training data
            num_frames: Number of video frames to use per sample
            image_size: (height, width) for resizing images
        """
        self.data_dir = Path(data_dir)
        self.num_frames = num_frames
        self.image_size = image_size

        # Find all source images and pair them with frame directories
        self.samples = []
        for source_path in sorted(self.data_dir.glob("source_*.png")):
            name = source_path.stem.replace("source_", "", 1)
            frames_dir = self.data_dir / f"frames_{name}"
            if frames_dir.exists():
                frame_files = sorted(frames_dir.glob("frame_*.png"))
                if len(frame_files) >= num_frames:
                    self.samples.append((source_path, frame_files))

        logger.info(f"Found {len(self.samples)} training samples in '{data_dir}'")

        self.image_transform = transforms.Compose([
            transforms.Resize(image_size),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5]),
        ])

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> dict:
        """
        Load a single training sample.

        Returns:
            Dict with:
                - 'source_image': Tensor [3, H, W] (normalized)
                - 'frames': Tensor [T, 3, H, W] (normalized video frames)
        """
        source_path, frame_files = self.samples[idx]

        # Load source image
        source_img = Image.open(source_path).convert("RGB")
        source_tensor = self.image_transform(source_img)

        # Load evenly spaced frames from the sequence
        frame_indices = torch.linspace(0, len(frame_files) - 1, self.num_frames).long()
        frames = []
        for i in frame_indices:
            frame = Image.open(frame_files[i]).convert("RGB")
            frames.append(self.image_transform(frame))

        frames_tensor = torch.stack(frames)  # [T, 3, H, W]

        return {
            "source_image": source_tensor,
            "frames": frames_tensor,
        }


# ---------------------------------------------------------------------------
# LoRA Setup
# ---------------------------------------------------------------------------

def setup_lora(unet: UNetSpatioTemporalConditionModel, lora_rank: int = 32) -> UNetSpatioTemporalConditionModel:
    """
    Apply LoRA adapters to the UNet.

    Args:
        unet: The SVD UNet model
        lora_rank: LoRA rank (higher = more parameters, better quality)

    Returns:
        UNet with LoRA adapters attached
    """
    lora_config = LoraConfig(
        r=lora_rank,
        lora_alpha=lora_rank,
        target_modules=["to_k", "to_q", "to_v", "to_out.0"],
        lora_dropout=0.0,
        bias="none",
    )
    unet = get_peft_model(unet, lora_config)
    unet.print_trainable_parameters()
    return unet


# ---------------------------------------------------------------------------
# Training Loop
# ---------------------------------------------------------------------------

def train_on_batch(args: argparse.Namespace, accelerator: Accelerator, epoch_num: int) -> None:
    """
    Train for 1 epoch on current batch data.

    Args:
        args: Parsed command line arguments
        accelerator: Accelerator instance
        epoch_num: Current epoch number (for logging)
    """
    # Load base SVD model components
    if epoch_num == 1:
        # First run: load base model
        logger.info(f"Loading base model: {args.base_model}")
        pipeline = StableVideoDiffusionPipeline.from_pretrained(
            args.base_model,
            torch_dtype=torch.float16 if args.mixed_precision == "fp16" else torch.float32,
        )
        
        vae = pipeline.vae
        image_encoder = pipeline.image_encoder
        unet = pipeline.unet
        scheduler = pipeline.scheduler
        feature_extractor = pipeline.feature_extractor
        
        vae.requires_grad_(False)
        image_encoder.requires_grad_(False)
        
        # Apply LoRA to UNet
        logger.info(f"Applying LoRA (rank={args.lora_rank}) to UNet...")
        unet = setup_lora(unet, lora_rank=args.lora_rank)
    else:
        # Resume from last checkpoint
        logger.info(f"Loading checkpoint from epoch {epoch_num - 1}...")
        checkpoint_dir = Path(args.output_dir) / f"lora_epoch_{epoch_num - 1}"
        
        pipeline = StableVideoDiffusionPipeline.from_pretrained(
            args.base_model,
            torch_dtype=torch.float16 if args.mixed_precision == "fp16" else torch.float32,
        )
        
        vae = pipeline.vae
        image_encoder = pipeline.image_encoder
        unet = pipeline.unet
        scheduler = pipeline.scheduler
        feature_extractor = pipeline.feature_extractor
        
        vae.requires_grad_(False)
        image_encoder.requires_grad_(False)
        
        # Load LoRA weights from checkpoint
        from peft import PeftModel
        unet = PeftModel.from_pretrained(unet, str(checkpoint_dir))

    # Enable gradient checkpointing to save memory
    if args.gradient_checkpointing:
        unet.enable_gradient_checkpointing()

    # ---------------------------------------------------------------------------
    # Dataset and DataLoader
    # ---------------------------------------------------------------------------
    dataset = LandslideDataset(
        data_dir=args.data_dir,
        num_frames=args.num_frames,
        image_size=(args.image_size, args.image_size),
    )

    if len(dataset) == 0:
        raise ValueError(f"No training samples found in '{args.data_dir}'. "
                         "Run data generation first.")

    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.dataloader_num_workers,
        pin_memory=False,
    )

    # ---------------------------------------------------------------------------
    # Optimizer
    # ---------------------------------------------------------------------------
    optimizer = torch.optim.AdamW(
        unet.parameters(),
        lr=args.learning_rate,
        betas=(0.9, 0.999),
        weight_decay=1e-2,
        eps=1e-8,
    )

    # LR scheduler for single epoch
    lr_scheduler = CosineAnnealingLR(optimizer, T_max=len(dataloader))

    # ---------------------------------------------------------------------------
    # Prepare with Accelerator
    # ---------------------------------------------------------------------------
    unet, optimizer, dataloader, lr_scheduler = accelerator.prepare(
        unet, optimizer, dataloader, lr_scheduler
    )

    vae = vae.to(accelerator.device)
    image_encoder = image_encoder.to(accelerator.device)

    # ---------------------------------------------------------------------------
    # Training Loop (1 epoch)
    # ---------------------------------------------------------------------------
    logger.info(f"Training epoch {epoch_num}/{args.num_epochs} with {len(dataset)} samples")

    unet.train()
    epoch_loss = 0.0

    progress_bar = tqdm(
        dataloader,
        desc=f"Epoch {epoch_num}/{args.num_epochs}",
        disable=not accelerator.is_local_main_process,
    )

    for step, batch in enumerate(progress_bar):
        with accelerator.accumulate(unet):
            source_images = batch["source_image"]  # [B, 3, H, W]
            video_frames = batch["frames"]          # [B, T, 3, H, W]

            B, T, C, H, W = video_frames.shape

            # Encode source images with CLIP image encoder
            with torch.no_grad():
                # Normalize to [0, 1] for CLIP feature extractor
                source_pil = (source_images * 0.5 + 0.5).clamp(0, 1)
                source_pil = (source_pil * 255).byte()

                # Process each image in the batch
                clip_inputs = []
                for i in range(B):
                    pil_img = Image.fromarray(
                        source_pil[i].permute(1, 2, 0).cpu().numpy()
                    )
                    processed = feature_extractor(pil_img, return_tensors="pt")
                    clip_inputs.append(processed.pixel_values)

                clip_pixel_values = torch.cat(clip_inputs, dim=0).to(accelerator.device)
                image_embeddings = image_encoder(clip_pixel_values).image_embeds
                # Add sequence dimension: [B, 1, D]
                image_embeddings = image_embeddings.unsqueeze(1)

            # Encode video frames to latents using VAE
            with torch.no_grad():
                # Flatten batch and time dims for VAE encoding
                frames_flat = video_frames.view(B * T, C, H, W)
                # Cast to VAE dtype to avoid MPS dtype mismatch
                frames_flat = frames_flat.to(vae.dtype)
                latents = vae.encode(frames_flat).latent_dist.sample()
                latents = latents * vae.config.scaling_factor
                # Reshape back: [B, T, latent_C, latent_H, latent_W]
                _, lC, lH, lW = latents.shape
                latents = latents.view(B, T, lC, lH, lW)

            # Rearrange for UNet: [B, lC, T, lH, lW]
            latents = latents.permute(0, 2, 1, 3, 4)

            # Sample noise and timesteps
            noise = torch.randn_like(latents)
            timesteps = torch.randint(
                0, scheduler.config.num_train_timesteps,
                (B,), device=accelerator.device
            ).long()

            # Add noise to latents
            noisy_latents = scheduler.add_noise(latents, noise, timesteps)

            # Prepare added time embedding (motion bucket id + fps)
            added_time_ids = _get_add_time_ids(
                fps=args.fps,
                motion_bucket_id=127,
                noise_aug_strength=0.02,
                batch_size=B,
                device=accelerator.device,
                dtype=latents.dtype,
            )

            # Encode conditioning frames (source image as video conditioning)
            with torch.no_grad():
                # Cast to VAE dtype to avoid MPS dtype mismatch
                source_latents = vae.encode(source_images.to(vae.dtype)).latent_dist.sample()
                source_latents = source_latents * vae.config.scaling_factor
                # Repeat for each timestep: [B, lC, 1, lH, lW] -> [B, lC, T, lH, lW]
                _, slC, slH, slW = source_latents.shape
                source_latents = source_latents.unsqueeze(2).expand(-1, -1, T, -1, -1)

            # Concatenate conditioning with noisy latents on channel dim
            latent_model_input = torch.cat([noisy_latents, source_latents], dim=1)

            # UNet forward pass
            noise_pred = unet(
                latent_model_input,
                timesteps,
                encoder_hidden_states=image_embeddings,
                added_time_ids=added_time_ids,
                return_dict=False,
            )[0]

            # Compute loss (MSE between predicted and actual noise)
            loss = F.mse_loss(noise_pred, noise, reduction="mean")

            accelerator.backward(loss)

            if accelerator.sync_gradients:
                accelerator.clip_grad_norm_(unet.parameters(), 1.0)

            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()

        epoch_loss += loss.detach().item()
        progress_bar.set_postfix({"loss": f"{loss.detach().item():.4f}"})

    avg_loss = epoch_loss / len(dataloader)
    logger.info(f"Epoch {epoch_num}/{args.num_epochs} | Loss: {avg_loss:.4f}")

    # Save checkpoint
    if accelerator.is_main_process:
        ckpt_dir = Path(args.output_dir) / f"lora_epoch_{epoch_num}"
        _save_lora_weights(accelerator.unwrap_model(unet), str(ckpt_dir))
        logger.info(f"Checkpoint saved: {ckpt_dir}")

    accelerator.end_training()


def download_batch_images(images_dir: str, num_images: int = 5) -> list[str]:
    """
    Download a batch of images from Wikimedia Commons.

    Args:
        images_dir: Directory to save images
        num_images: Number of images to download in this batch

    Returns:
        List of downloaded image file paths
    """
    from download_images import SEARCH_QUERIES
    import time
    import requests
    
    WIKIMEDIA_API = "https://commons.wikimedia.org/w/api.php"
    HEADERS = {
        "User-Agent": "MLCrumblingAlps/1.0 (https://github.com/Mass23/ML_crumblingalps; massimo.bourquin@gmail.com)"
    }
    REQUEST_DELAY = 1.0

    images_dir = Path(images_dir)
    images_dir.mkdir(parents=True, exist_ok=True)
    
    attr_path = images_dir.parent / "attributions.json"
    attributions = load_attributions(attr_path)
    
    downloaded_paths = []
    downloaded_count = 0

    logger.info(f"Downloading {num_images} new images for this batch...")

    for query in SEARCH_QUERIES:
        if downloaded_count >= num_images:
            break

        remaining = num_images - downloaded_count
        per_query = min(50, remaining)

        logger.info(f"  Searching: '{query}' (need {remaining} more images)...")
        time.sleep(REQUEST_DELAY)

        pages = search_wikimedia_images(query, limit=per_query)

        for page in pages:
            if downloaded_count >= num_images:
                break

            image_info = extract_image_info(page)
            if image_info is None:
                continue

            filename = image_info["filename"]

            # Skip if already downloaded
            if filename in attributions and (images_dir / filename).exists():
                logger.info(f"    Skipping (already tracked): {filename}")
                continue

            logger.info(f"    Downloading: {filename}")

            time.sleep(REQUEST_DELAY)
            success = download_image(image_info, images_dir)

            if success:
                attributions[filename] = {
                    "filename": filename,
                    "title": image_info["title"],
                    "source_url": image_info["source_url"],
                    "author": image_info["author"],
                    "license": image_info["license"],
                    "license_url": image_info["license_url"],
                    "width": image_info["width"],
                    "height": image_info["height"],
                }
                save_attributions(attributions, attr_path)
                downloaded_paths.append(str(images_dir / filename))
                downloaded_count += 1

    logger.info(f"Downloaded {downloaded_count} images for this batch")
    return downloaded_paths


def clear_training_data(data_dir: str) -> None:
    """
    Clear all training data from directory to save space.

    Args:
        data_dir: Directory containing training data
    """
    data_path = Path(data_dir)
    if data_path.exists():
        logger.info(f"Clearing training data from {data_dir}...")
        shutil.rmtree(data_path)
        data_path.mkdir(parents=True, exist_ok=True)
        logger.info(f"Training data cleared")


def batch_training_pipeline(args: argparse.Namespace) -> None:
    """
    Batch training pipeline:
      1. For each epoch (up to num_epochs):
         a. Download 5 new images
         b. Generate training data
         c. Train for 1 epoch
         d. Save checkpoint
         e. Clear training data
         f. Repeat

    Args:
        args: Parsed command line arguments
    """
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with="tensorboard" if args.report_to == "tensorboard" else None,
        project_dir=args.output_dir,
    )

    logging.basicConfig(
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        datefmt="%m/%d/%Y %H:%M:%S",
        level=logging.INFO,
    )

    if args.seed is not None:
        set_seed(args.seed)

    # Create output directory
    output_dir = Path(args.output_dir)
    if accelerator.is_main_process:
        output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("=== BATCH TRAINING PIPELINE ===")
    logger.info(f"Total epochs: {args.num_epochs}")
    logger.info(f"Images per batch (epoch): {args.batch_size}")
    logger.info(f"Total images to process: {args.num_epochs * args.batch_size}")

    # Main loop: one epoch = one batch of 5 images
    for epoch_num in range(1, args.num_epochs + 1):
        logger.info(f"\n{'='*60}")
        logger.info(f"EPOCH {epoch_num}/{args.num_epochs}")
        logger.info(f"{'='*60}")

        # Step 1: Download new images
        downloaded_images = download_batch_images(args.images_dir, args.batch_size)
        
        if not downloaded_images:
            logger.warning("No new images downloaded, skipping this epoch")
            continue

        # Step 2: Generate training data
        logger.info(f"Generating training data for {len(downloaded_images)} images...")
        process_image_batch(
            downloaded_images,
            args.data_dir,
            duration=args.duration,
            fps=args.fps,
            target_width=args.target_width,
            target_height=args.target_height,
        )

        # Step 3: Train on this batch (1 epoch)
        logger.info(f"Training on batch {epoch_num}/{args.num_epochs}...")
        train_on_batch(args, accelerator, epoch_num)

        # Step 4: Clear training data to save space
        if epoch_num < args.num_epochs:  # Don't clear on last epoch
            clear_training_data(args.data_dir)

    logger.info(f"\n{'='*60}")
    logger.info("BATCH TRAINING PIPELINE COMPLETE")
    logger.info(f"Total epochs trained: {args.num_epochs}")
    logger.info(f"Total images processed: {args.num_epochs * args.batch_size}")
    logger.info(f"Final checkpoint: {output_dir / f'lora_epoch_{args.num_epochs}'}")
    logger.info(f"{'='*60}")


def _get_add_time_ids(
    fps: int,
    motion_bucket_id: int,
    noise_aug_strength: float,
    batch_size: int,
    device: torch.device,
    dtype: torch.dtype,
) -> torch.Tensor:
    """
    Build the added time embedding tensor for SVD conditioning.

    Args:
        fps: Frames per second
        motion_bucket_id: Motion bucket ID for conditioning
        noise_aug_strength: Augmentation noise strength
        batch_size: Batch size
        device: Target device
        dtype: Target dtype

    Returns:
        Tensor of shape [B, 3]
    """
    add_time_ids = [fps - 1, motion_bucket_id, noise_aug_strength]
    add_time_ids = torch.tensor([add_time_ids], dtype=dtype, device=device)
    add_time_ids = add_time_ids.repeat(batch_size, 1)
    return add_time_ids


def _save_lora_weights(unet: UNetSpatioTemporalConditionModel, save_dir: str) -> None:
    """
    Save LoRA weights to disk.

    Args:
        unet: The UNet model (with LoRA adapters)
        save_dir: Directory to save weights
    """
    Path(save_dir).mkdir(parents=True, exist_ok=True)
    unet.save_pretrained(save_dir)


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Batch train Stable Video Diffusion with LoRA on landslide data"
    )

    # Data arguments
    parser.add_argument("--data-dir", type=str, required=True,
                        help="Directory for temporary training data (gets cleared between batches)")
    parser.add_argument("--images-dir", type=str, required=True,
                        help="Directory where raw downloaded images are stored")
    parser.add_argument("--output-dir", type=str, default="checkpoints",
                        help="Directory for saving checkpoints (default: checkpoints)")
    parser.add_argument("--base-model", type=str,
                        default="stabilityai/stable-video-diffusion-img2vid",
                        help="HuggingFace model ID for the base SVD model")

    # Training hyperparameters
    parser.add_argument("--num-epochs", type=int, default=300,
                        help="Number of epochs/batches to process (default: 300)")
    parser.add_argument("--batch-size", type=int, default=5,
                        help="Images per batch/epoch (default: 5)")
    parser.add_argument("--learning-rate", type=float, default=1e-4,
                        help="Learning rate (default: 1e-4)")
    parser.add_argument("--gradient-accumulation-steps", type=int, default=4,
                        help="Gradient accumulation steps (default: 4)")
    parser.add_argument("--mixed-precision", type=str, default="fp16",
                        choices=["no", "fp16", "bf16"],
                        help="Mixed precision training (default: fp16)")
    parser.add_argument("--gradient-checkpointing", action="store_true",
                        help="Enable gradient checkpointing to save memory")
    parser.add_argument("--dataloader-num-workers", type=int, default=4,
                        help="Number of DataLoader workers (default: 4)")

    # LoRA arguments
    parser.add_argument("--lora-rank", type=int, default=32,
                        help="LoRA rank (default: 32)")

    # Video arguments
    parser.add_argument("--num-frames", type=int, default=14,
                        help="Number of video frames per sample (default: 14)")
    parser.add_argument("--image-size", type=int, default=512,
                        help="Image size in pixels (default: 512)")
    parser.add_argument("--fps", type=int, default=14,
                        help="Frames per second for conditioning (default: 14)")
    parser.add_argument("--duration", type=int, default=4,
                        help="Video duration in seconds (default: 4)")
    parser.add_argument("--target-width", type=int, default=2880,
                        help="Target image width in pixels (default: 2880)")
    parser.add_argument("--target-height", type=int, default=1620,
                        help="Target image height in pixels (default: 1620)")

    # Logging
    parser.add_argument("--report-to", type=str, default="tensorboard",
                        choices=["tensorboard", "none"],
                        help="Where to log training metrics (default: tensorboard)")
    parser.add_argument("--seed", type=int, default=42,
                        help="Random seed for reproducibility (default: 42)")

    args = parser.parse_args()
    batch_training_pipeline(args)


if __name__ == "__main__":
    main()